name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Set up Android SDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Set up Android SDK
      uses: actions/setup-android@v2
      with:
        sdk-platform: '29'

    - name: Install Buildozer dependencies
      run: |
        buildozer android debug requirements

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./bin/

    # ... other steps as needed
